spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json



server:
  servlet:
    context-path: /api/v1/